name: CI
run-name: ${{ github.actor }} is testing
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Install alsa and udev
        run: sudo apt update; sudo apt install -f libasound2-dev libudev-dev libgtk-3-dev libwebkit2gtk-4.1-dev libsoup-3.0-dev libxdo-dev
        if: runner.os == 'linux'
      - name: Test all features
        run: cargo test --all-features --all
      - name: Clippy all features
        run: cargo clippy --tests --all-targets --all-features -- -D warnings
